export const PELANGGAN_INSERTED = 'PELANGGAN_INSERTED';
export const PAYMENT_INSERTED = 'PAYMENT_INSERTED';
export const BIAYA_TRIGGER = 'BIAYA_TRIGGER';
export const PENGIRIMAN_TRIGGER = 'PENGIRIMAN_TRIGGER';
export const ROLE_TRIGGER = 'ROLE_TRIGGER';
